export const constants = {
  KEY_SOCIODEMOGRAPHIC: 'DATOS_SOCIODEMOGRAFICOS',
  KEY_GENERALPATIENTDATA: 'DATOS_GENERALES',
  KEY_DIAGNOSIS: 'DIAGNOSTICOS',
  KEY_TRACING: 'SEGUIMIENTO',
  KEY_COMPLEMENTARYIMAGINGGSCANS: 'EXPLORACION_COMPLEMENTARIA',
  KEY_ADHERENCETOTREATMENT: 'ADHERENCIA_AL_TRATEMIENTO',
  KEY_CONSENT: 'CONSENTIMIENTO',
};
