export const constants = {
  keyPhysicalCondition: 'physical-condition',
  keyWorkGroups: 'work-groups',
  keyConsumptionHabits: 'consumption-habits',
  keyPrincipalDiagnosis: 'principal-diagnosis',
  keySecundaryDiagnosis: 'secundary-diagnosis',
  keyComorbidities: 'comorbidities',
  keySocioDermographic: 'sociodemographic-data',
  keyGeneralPatientData: 'general-patient-data',
  keyDiagnosis: 'diagnosis',
  keyTracing: 'tracing',
  keyComplementaryImaginScans: 'complementary-imaging-scans',
  keyAdherenceToTreatment: 'adherence-to-treatment',
  keyConsent: 'consent',
  keyFamilyHistory: 'family-history',
  keyBloodCount: 'blood-count',
  keyMetabolicProfile: 'metabolic-profile',
  keyKidneyLiverBiochemistry: 'kidney-liver-biochemistry',
  keySerology: 'serology',
  keyLeikocyteAntibodyAntigen: 'leukocyte-antibody-antigen',
  keyBiologicalDrugMonitoring: 'biological-drug-monitoring',
  keySharedPatient: 'shared-patients',
  eavPase: 'eav-pase'
};
