export interface MimeType {
    extension: string;
    type: string;
}

export const MimeTypes: Array<MimeType> = [
    { extension: 'aac', type: 'audio/aac' },
    { extension: 'abw', type: 'application/x-abiword' },
    { extension: 'arc', type: 'application/octet-stream' },
    { extension: 'avi', type: 'video/x-msvideo' },
    { extension: 'azw', type: 'application/vnd.amazon.ebook' },
    { extension: 'bin', type: 'application/octet-stream' },
    { extension: 'bz', type: 'application/x-bzip' },
    { extension: 'bz2', type: 'application/x-bzip2' },
    { extension: 'csh', type: 'application/x-csh' },
    { extension: 'css', type: 'text/css' },
    { extension: 'csv', type: 'text/csv' },
    { extension: 'doc', type: 'application/msword' },
    { extension: 'epub', type: 'application/epub+zip' },
    { extension: 'gif', type: 'image/gif' },
    { extension: 'htm', type: 'text/html' },
    { extension: 'html', type: 'text/html' },
    { extension: 'ico', type: 'image/x-icon' },
    { extension: 'ics', type: 'text/calendar' },
    { extension: 'jar', type: 'application/java-archive' },
    { extension: 'jpeg', type: 'image/jpeg' },
    { extension: 'jpg', type: 'image/jpeg' },
    { extension: 'js', type: 'application/javascript' },
    { extension: 'json', type: 'application/json' },
    { extension: 'mid', type: 'audio/midi' },
    { extension: 'midi', type: 'audio/midi' },
    { extension: 'mpeg', type: 'video/mpeg' },
    { extension: 'mpkg', type: 'application/vnd.apple.installer+xml' },
    { extension: 'odp', type: 'application/vnd.oasis.opendocument.presentation' },
    { extension: 'ods', type: 'application/vnd.oasis.opendocument.spreadsheet' },
    { extension: 'odt', type: 'application/vnd.oasis.opendocument.text' },
    { extension: 'oga', type: 'audio/ogg' },
    { extension: 'ogv', type: 'video/ogg' },
    { extension: 'ogx', type: 'application/ogg' },
    { extension: 'pdf', type: 'application/pdf' },
    { extension: 'ppt', type: 'application/vnd.ms-powerpoint' },
    { extension: 'rar', type: 'application/x-rar-compressed' },
    { extension: 'rtf', type: 'application/rtf' },
    { extension: 'sh', type: 'application/x-sh' },
    { extension: 'svg', type: 'image/svg+xml' },
    { extension: 'swf', type: 'application/x-shockwave-flash' },
    { extension: 'tar', type: 'application/x-tar' },
    { extension: 'tif', type: 'image/tiff' },
    { extension: 'tiff', type: 'image/tiff' },
    { extension: 'ttf', type: 'font/ttf' },
    { extension: 'txt', type: 'text/plain' },
    { extension: 'vsd', type: 'application/vnd.visio' },
    { extension: 'wav', type: 'audio/x-wav' },
    { extension: 'weba', type: 'audio/webm' },
    { extension: 'webm', type: 'video/webm' },
    { extension: 'webp', type: 'image/webp' },
    { extension: 'woff', type: 'font/woff' },
    { extension: 'woff2', type: 'font/woff2' },
    { extension: 'xhtml', type: 'application/xhtml+xml' },
    { extension: 'xls', type: 'application/vnd.ms-excel' },
    { extension: 'xml', type: 'application/xml' },
    { extension: 'xul', type: 'application/vnd.mozilla.xul+xml' },
    { extension: 'zip', type: 'application/zip' },
    { extension: '7z', type: 'application/x-7z-compressed' },
];
